### ISSUE TITLE
RPC between Release and Debug programs causes segfaults

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#10]
If a Derecho program is compiled in "release" mode on some nodes and "debug" mode on other nodes, it will crash at runtime when any RPC messages go between the "release" and "debug" nodes. This appears to be because the "release" binaries have different `type_index`es than the "debug" binaries for the same classes (e.g. `type_index(typeinfo(Foo))` will have a different value depending on whether the compiler was in Release or Debug mode). As a result, when an RPC message from a "release" node arrives on a "debug" node and RPCManager attempts to read the `type_index` in the message's `Opcode`, it crashes with a segmentation fault because the `type_index` does not point to any valid type.

**Comment by mpmilano** [comment]
WONTFIX, it is a feature that without -DNDEBUG the serialized representations include explicit message headers and string descriptions for, well, debugging.  

In general, mixing debug and non-debug is dangerous; we assume identical code running at all nodes, and having some nodes compiled with -DNDEBUG and others without will challenge that assumption.  If we want to allow this feature, we should sit down and think about how to ensure we did it correctly.

**Comment by etremel** [comment]
Oh, I didn't realize this was an intentional feature of "Debug" mode; I thought it just switched compiler flags (e.g. -ggdb), and a compiler-only change shouldn't break our RPC. But if Debug mode actually changes the code (by adding stuff to serialized objects) then of course it makes sense that it won't interoperate with Release mode.

**Comment by mpmilano** [comment]
I'm not sure that's entirely unique to the serialization library either... you should check the codebase for the strings `whendebug` and `DNDEBUG` and see what comes up.  It's entirely possible that there are other code differences lurking to be found.
