### ISSUE TITLE
ObjectStore client-side put is blocking

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#105]
The ObjectStore uses different code paths to handle the requests from replica nodes and client nodes. The replica nodes are in the ObjectStore subgroup and can send an `ordered_query` to do the work. However, a client has to relay the request to a replica node with `p2p_query`. In such a situation, I noticed that the requested replica node blocks on trying to collect the RPC reply from remote nodes sent by p2p messages. This relates to #70.

**Comment by KenBirman** [comment]
Ken’s theory: Weijia is in a thread doing an upcall that isn’t allowed to block, but he is using a blocking call and so he ties up the thread and causes the deadlock

Sent from my iPhone

On Mar 1, 2019, at 9:17 AM, Weijia Song <notifications@github.com<mailto:notifications@github.com>> wrote:


The ObjectStore use different code path to handle the requests from replica nodes, where data is stored, and client nodes. The replica nodes are in the ObjectStore subgroup and can just send an ordered_query to do all the work. However, a client has to relay the request to a replica node with p2p_query. In such a situation, I noticed that the requested replica node is blocked on trying to collect the RPC replies from remote nodes sent by p2p messages. This relates to #70<https://github.com/Derecho-Project/derecho-unified/issues/70>.

**Comment by KenBirman** [comment]
Suggestion: if user code is running in an upcall from a Derecho thread (the p2p thread or the trigger thread), watch for falls into blocking methods like ordered_send or p2p_send/query and throw an exception.  Makes more sense than deadlocking silently!

**Comment by mpmilano** [comment]
Most of the reason we have these monolithic locks in the first place is because of the underlying RDMC buffer; we need to wait for the user program to be finished with it before we can re-use it.  If we're ditching the buffer-based round-robin approach from RDMC (as I believe is the plan), then we can also avoid these locks; take the buffer in question out of rotation until the user code is done with it.  So best of both worlds --- users can issue more sends/queries in send/query handlers, and Derecho can avoid blocking!

**Comment by KenBirman** [comment]
My concern centers on cases where we only have a single thread that does an upcall to a lambda and where the lambda must not block or Derecho would freeze up.

**Comment by songweijia** [comment]
I check the code. Ken's theory is right. I should implement the RPC calls non-blocking, just as the traditional "top half" of the interrupt handler. In this particular situation, I issued an ordered query in the p2p RPC function, which blocks the `RPCManager::p2p_receive_loop()` thread. But the ordered query requires the p2p_receive_loop to be alive to collect the remote return values sent with P2P RPC message. As Ken suggested, I plan to offload the p2p query task to an agent thread with a FIFO queue buffer interface.

It would be great that the derecho core can avoid the blocking as Matt suggested. This is our purpose in #70.

**Comment by songweijia** [comment]
Solved by separating the RPC reply and P2P Send/Query path in commit 85037951654db085c45c4ea4a7a26c7724a51b89
