### ISSUE TITLE
Complete state transfer before confirming restart view

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#106]
The correct algorithm for restarting a Derecho group from a total failure requires all restarting nodes to complete state transfer (downloading log entries from the "restart shard leaders") before the restart View can be confirmed; it is not safe to record the restart View unless all of its members are up to date and could be used for a further restart. However, the way we currently have it implemented, state transfer happens after everyone has confirmed the restart view, because we reused the code path from the normal case of a node joining the system (in which it first receives the view and then does state transfer). We should make the state transfer process happen before the view is confirmed in the total restart case, even if it means adding a semi-redundant code path.

**Comment by sagarjha** [comment]
@etremel Your recent commits break the view change process when a new node joins a subgroup and needs to receive state from the old shard leader. I am running `applications/archive/membership_tests` with arguments `1 0 0 0` on 4 nodes starting them one by one with a delay. When the fourth node joins the group, there's a deadlock where the 4th member is waiting to add a connection to the third member while the third member is waiting to receive state from the second member. Please fix.

**Comment by sagarjha** [comment]
Thanks Edward for fixing it!
