### ISSUE TITLE
Carefully check for race conditions involving SST entries

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#108]
There is a race condition in the following code:
`message_id_t min_stable_num
        = sst.seq_num[node_id_to_sst_index.at(curr_subgroup_settings.members[0])][subgroup_num];
for(uint i = 0; i < num_shard_members; ++i) {
        if(sst.seq_num[node_id_to_sst_index.at(curr_subgroup_settings.members[i])][subgroup_num] < min_stable_num) {
        min_stable_num = sst.seq_num[node_id_to_sst_index.at(curr_subgroup_settings.members[i])][subgroup_num];
    }
}`

Here, we are going through a column of the SST (for members that belong to a shard), and updating the minimum value seen for each new value in the column if it is less than the minimum.

We are reading the same SST entry twice if we find that we need to update the minimum. If that entry changes between the two reads, then we have a race condition. For example,
suppose that seq_num column is 8 7 10. We look at the first entry and set the minimum to 8. Then, we see that 7 < 8, so we proceed to update min to the second entry. But, just before that, that entry updates itself to 10 (because the owner of the corresponding row pushed a write indicating the receipt of 3 more messages). Now minimum is set to 10 when the column is still 8 10 10. To fix this issue, we need to make sure that we read each SST entry into a local variable. Something like this is needed:
`message_id_t min_stable_num
        = sst.seq_num[node_id_to_sst_index.at(curr_subgroup_settings.members[0])][subgroup_num];
for(uint i = 0; i < num_shard_members; ++i) {
    min_stable_num = std::min(min_stable_num, (message_id_t)sst.seq_num[node_id_to_sst_index.at(curr_subgroup_settings.members[i])][subgroup_num]);
}`

**Comment by KenBirman** [comment]
Worse, if the SST isn’t properly declared, a C++ compiler could strip out that copy into a helper variable!  You need to declare the SST as volatile to be sure this will work...

**Comment by sagarjha** [comment]
We have the correct volatile qualifiers throughout the code.
