### ISSUE TITLE
Deadlock on ordered_query in special case.

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#109]
The lock on `RemoteInvoker::map_lock` will cause a deadlock at some circumstance. `RemoteInvoker::map_lock` protects RemoteInvoker::results_map from concurrent access. Sometimes, an ordered_query may be handled faster on the remote than the local so that the node issuing ordered_query receives a corresponding reply via P2P message before it finishes handling this ordered_query itself. Therefore, the `rpc_thread` hold the `RemoteInvoker::map_lock` on results_map, and waiting for the 'promise' future to be fulfilled (Yes, it's intuitive: a promise future is not a result future. Fulfilling a promise future means the promise for result future(s) has been prepared.). However, the predicate thread ('sst_detect') cannot fulfill the future because it waits on `RemoteInvoker::map_lock` before that (call the `set_value` on the future). See, deadlock: the two paths collide at Line 145 and 151 in file `remote_invocable.h`.

My proposal is to check whether the promise future is valid or not with a condition variable. Then the local predicate thread will not block on handling corresponding ordered_query. Please let me know if you do not agree with my solution. I might start to fix it as soon.

**Comment by songweijia** [comment]
Need more investigation...close for now.

**Comment by songweijia** [comment]
The fix is to use a fine lock granularity. The `RemoteInvoker::map_lock` only protects the results_map from concurrent inserts and retrieves. Each `PendingResults` has another lock protecting concurrent accesses to the promise. See commit 849aa881001258026aac9903eeef2824ea7d8312.

**Comment by mpmilano** [comment]
I agree with the "increase granularity" fix but honestly I think an even better one would be to systematically replace the STL datastructures that we use concurrently with actual concurrent versions.  So kill map-lock and the pending-results locks, and replace the map itself with a highly-concurrent implementation.
