### ISSUE TITLE
PersistenceManager deadlocks on shutdown

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#14]
Any experiment that creates a Group does not exit cleanly, instead hanging forever at the end of main(). The culprit is that Group's destructor calls `PersistenceManager::shutdown()`, which hangs forever waiting on `persist_thread.join()`. At this point, the persist thread is waiting on the semaphore `persistence_request_sem`, which will never be incremented because there are no more persistence requests.

I have two suggested fixes, but I think it's up to Weijia which one to implement, since he wrote PersistenceManager.

1.  Change `persistence_request_sem` to a condition variable, and make the condition predicate something like `!persistence_request_queue.empty() || thread_shutdown` so that the thread wakes when there is a shutdown request even if there are no persistence requests.
2. Add `sem_post(&persistence_request_sem)` to `shutdown()`, and add some logic to the persistence thread to check whether it was awakened because there is a new request on `persistence_request_queue` or because `shutdown()` was called.

**Comment by songweijia** [comment]
Thank you for finding out this bug. I took the second option. Just checked in. The code hasn't been tested yet. Let's try it tomorrow.
