### ISSUE TITLE
Persistence request queue is not thread-safe

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#19]
PersistenceManager uses a `std::queue` to store persistence requests, which are enqueued by the SST predicate thread and dequeued by the persist thread. However, `std::queue` is not thread-safe, even for the seemingly easy case of a single producer and single consumer thread. We should either add a mutex for `persistence_request_queue` to prevent concurrent access, or switch to the thread-safe concurrent queue written by MoodyCamel, available [here](https://github.com/cameron314/concurrentqueue).

**Comment by songweijia** [comment]
Now persistence_request_queue is guarded by a spinlock implemented using std::atomic_flag. This update is in commit a2dab9e9f42b0ab3e1ba795ded9a8ae2961a296c on 'libfabric' branch. It is going to be merged in 'master' soon.
