### ISSUE TITLE
View change during ordered_query can make clients hang

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#21]
When a client application thread calls `ordered_query` on a Replicated object, it immediately gets a `QueryResults<T>` as soon as the send completes *locally*, i.e. `multicast_group->send()` returns. In order to actually inspect the results of the query, the client must call `QueryResults<T>::get()` on the QueryResults object, which returns a ReplyMap only when the systems knows the set of nodes the query was sent to.

The ReplyMap that `QueryResults<T>::get()` waits for is fulfilled when the sending node first receives the ordered query RPC message to itself. Specifically, `RPCManager::rpc_message_handler()` calls `fulfill_map()` on a `PendingResults<T>`, which is the "promise end" of a `QueryResults<T>`, when it receives an RPC message from its own Node ID. However, `rpc_message_handler()` is only called when an RPC (that is, ordered query) message is *globally stable*. 

The problem is that a view change can result in a locally "sent" message never becoming globally stable, because it is trimmed away during ragged edge cleanup. In this case the client thread will get a QueryResults for its ordered query (because the send completed locally), but the ReplyMap for that QueryResults will never be fulfilled because the message corresponding to that ordered query was trimmed and will never be delivered. The client is never notified of the fact that their query failed to send, and waits forever on `QueryResults<T>::get()`.

**Comment by mpmilano** [comment]
Agree with first option; this should result in an exception.  At the worst, it's a similar user experience to the "woke for no visible reason" exception found in java's threading.

**Comment by sagarjha** [comment]
Result of the bug in https://github.com/Derecho-Project/derecho-unified/issues/22
