### ISSUE TITLE
Redirect joining nodes if they contact the wrong leader

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#28]
Currently, we expect any node that joins an existing group (i.e. start up as a non-leader) to know the correct IP address of the current top-level group leader when it runs the Group constructor. If the joining node contacts a group member that is not the current leader, it will hang forever, because all nodes run the background thread that accepts incoming connections, but only the leader will actually respond to incoming connections (by proposing a new view and then sending it to the joiner). 

Instead, it would be better if non-leader nodes responded to incoming connections by replying with the IP address of the current leader and then closing the connection, so that the node attempting to join could retry with the correct IP address.

**Comment by etremel** [comment]
This has been implemented as of 3bd69e94, which worked correctly after all.

**Comment by sagarjha** [comment]
@songweijia, this is what you wanted.
