### ISSUE TITLE
Long delays for some P2P queries and send operations

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#3]
Peer-to-peer RPC calls, which are currently run over a persistent TCP connection, occasionally take much longer than normal (i.e. 15ms instead of 1ms) to complete. This was documented by @songweijia in his experiments with inter-shard queries. Below is his graph of p2p_query() latency over a series of trials:
![p2p_query_call_latency](https://user-images.githubusercontent.com/2080569/30437767-73ef6022-993d-11e7-9ce1-f3b5ef317e29.png)

**Comment by sagarjha** [comment]
Irrelevant for more than a year now since we have switched to RDMA for the P2P layer.
