### ISSUE TITLE
Get rid of tcp connections in RPCManager

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#32]
RPCManager no longer needs to manage tcp connections as RDMA is now used to send P2P requests and replies. So we should either get rid of `tcp_connections` or move it to where it is used. Then we will not have to call `get_socket` in `rpc_manager.cpp` to get the socket to a node.

**Comment by etremel** [comment]
I already refactored `tcp_connections` out of RPCManager in commit 472f66116ab5cd8c6b44828945e71acf2601922f in my branch failure_restart_improvements. This will be fixed as soon as we can merge this branch back into master.

**Comment by etremel** [comment]
This has now been fixed in master, as of 5d36d09393b370c1be6559a97fd10d9c95b5158b
