### ISSUE TITLE
constness and cooked arguments

### ISSUE THREAD

**Issue by mpmilano** [Derecho-Project/derecho-unified#35]
We appear to be requiring `const`-only arguments for remote procedure calls.  This is an unnecessary restriction.  Allowing more flexible invocations will require eliminating the assumption that receive-buffers are `const` during RPC.  I think this is a fine thing to do, but want to check with everyone first to make sure there's not some subtle immutability assumption we're relying on.

**Comment by sagarjha** [comment]
I don't think we have this restriction. See function `Foo:change_state` in `derecho/experiments/test_objects.h` which takes an integer `new_state`. It is used in `derecho/experiments/typed_subgroup_test.cpp`. Also see the file `derecho_caller_test.cpp`.

**Comment by mpmilano** [comment]
Sorry, I should have specified that *when taking their arguments by reference*, we require references be `const`-qualified.  We want every large argument taken by reference (and returned by reference, ideally, but that's another bug) to avoid automatic copying. 

There's an argument to be made for requiring reference arguments to be const-qualified; they're ephemeral objects, and most intentional modification of arguments happens in order to persist those effects after the method has returned.  But there's also the simple reality that lots of common structures, especially those inherited from C, aren't going to support convenient const-qualified access.
