### ISSUE TITLE
Make sure orderedSend does not get replies

### ISSUE THREAD

**Issue by mpmilano** [Derecho-Project/derecho-unified#40]
Based on the shared codepath between ordered query and ordered send, we do not seem to indicate to the RPC receiver whether a reply is desired to a particular event.  We should indicate this for performance reasons; why send a reply when nobody's looking?

**Comment by mpmilano** [comment]
follow-up: orderedSend appears broken for non-void functions.  Same change should fix both

**Comment by etremel** [comment]
Note that as of 09d165046f770217b04e6a0988582d4cf5d7cbac, ordered_send and ordered_query are now combined into a single function that handles both void and non-void functions, which makes your second issue a moot point. This also means that a user cannot invoke a non-void function through the "reply-ignoring" ordered_send; they are now guaranteed to get a QueryResults that waits for replies if they invoke a non-void function. Do you still think that we should indicate whether users are actually going to look at the replies returned to the QueryResults, and not send replies if they will be ignored? I don't know if there's a good way to detect whether the user uses or ignores the returned QueryResults.

**Comment by sagarjha** [comment]
Should we close this issue @mpmilano @etremel?
