### ISSUE TITLE
Update and synchronize README

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#5]
After we finish implementing pending changes to the Derecho RPC API (such as #2 and #4), we should update the repository's README and the corresponding page on derecho-project.github.io.

**Comment by songweijia** [comment]
I can help with the part for persistent<T>/volatile<T>. BTW, we need to include a section for configuration/performance optimization. For example, "vm.overcommit_memory=1" needs to be set in sysctl.conf to allow the initialization of persistent<T> memory map.
