### ISSUE TITLE
Local Derecho: avoid /dev/shm conflicts

### ISSUE THREAD

**Issue by mpmilano** [Derecho-Project/derecho-unified#56]
In order to support multiple concurrent Derecho instances on the same computer, we're going to want to suffix any Derecho-related files with the PID (or something similar).

**Comment by songweijia** [comment]
Solved: using the pid as namespace, and also configurable through derecho.cfg. See [this commit](https://github.com/Derecho-Project/derecho-unified/commit/ae4c668d9aea14cf1665ae795c8dcea9bc4c2809).
