### ISSUE TITLE
derecho/experiments/p2p_query_test.cpp is broken.

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#59]
Some node aborted once finished group setup procedure:

```
Foo function setting next_unassigned_rank to 3
Bar function setting next_unassigned_rank to 3
Cache function setting next_unassigned_rank to 5
Initialized SST and Started Threads
Initialization complete
Initialization complete
The persist thread started
Finished constructing/joining Group
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted
```
Found on commit d86a72d5eac7c0221cf8383e64273297337cc0e2

**Comment by sagarjha** [comment]
The test works fine because we are supposed to start the nodes one by one in order, not all at the same time. When we have a proper test suite, we should document how to run each test.

**Comment by songweijia** [comment]
IN CASE OF libfabric over TCP/IP: Libfabric will always pick the first IP address of a NIC in case of multiple IP configuration. That will cause an issue if the FIRST IP addresses of the nodes are in different subnets.
