### ISSUE TITLE
Use RDMA for P2P queries within the system

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#6]
Currently, `p2p_send` and `p2p_query` use TCP connections because they happen outside of established RDMC groups, and could be sent by a process that isn't even part of the top-level Derecho group. However, for many of our proposed use cases for `p2p_query`, the querying process is another node on the same RDMA network as the Derecho group, and might even be a Derecho group member that's simply querying a subgroup/shard it's not a member of. We should use RDMA for P2P queries whenever possible, especially since the reply from a P2P query might be a large amount of ReplicatedObject state.

**Comment by sagarjha** [comment]
RDMA for P2P connections is now available in master. On the p2p_to_rdma branch, average latency for one P2P request is about 8-10 microseconds, which is about the time it takes to make two RDMA operations. This makes sense as it includes time to serialize, deserialize, send a P2P request, get back a P2P reply etc.
The design is similar to that for SST multicast. There's a window of slots that contain these requests and replies. Also, the replies from the ordered sends/receive use these connections.
