### ISSUE TITLE
Separate leader port and local port

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#60]
For running multiple derecho instances on a single node as different processes, the nodes need to use different ports for TCP connections. However, ports for all the nodes are assumed to be the same in the code currently. Instead we can provide the leader port as an input and have the port for the local node in the config file. Then the leader can be contacted by any starting member and the leader can then share the port of the existing members so that other nodes can be contacted. This can be conveniently achieved by sharing the ports using the SST, just as IP addresses currently are shared.

**Comment by KenBirman** [comment]
Whoever tackles this change might consider just having us store a Linux ip_addr struct, rather than treating IP addresses as an int_32 and adding an additional int_32 for the port number.  The standard Linux struct has a type field (IPv4 or IPv6), a value field, and a field for the port number.  So the code change is minimized (one int_32 becomes one instance of the struct), existing code that needs the IP address does need to change but in a fairly simple way, and we benefit because of some network out there is pure IPv6, we could run on it rather than being limited to IPv4 networks.

**Comment by sagarjha** [comment]
Related to this issue, we verified that Derecho works on a local machine. We tested:
1. Separate derecho instances on the same set of machines
2. Derecho test with two VMs on the same machine
3. Derecho test with a VM and a different laptop
4. Derecho test with a VM and a Fractus machine

**Comment by KenBirman** [comment]
It would be worth the effort to think about situations where some Derecho processes are TCP only (and yes, not locked to specific port numbers unless capable of playing the leader role), while some have RDMA interfaces and “switch” to those if all members of a given subgroup or shard are equally capable.

Then we could have a big group, a rack of RDMA-capable servers, and a larger set of TCP-only “clients” using the LibFabrics to TCP mapping, but still benefitting from the high efficiency of that version of TCP, the zero-copy marshalling logic, etc.  I think this might be an ideal mix, in the long term, for many developers

**Comment by sagarjha** [comment]
While that is definitely something to do in the long run because we will have clients outside the system unable to use RDMA, we currently only support all TCP or all RDMA nodes. Weijia might know how much time implementing this will take.
The feature will be that every node can join the group regardless of whether they use TCP or RDMA (but only one). All nodes can talk to all nodes. So if a subgroup has some members using RDMA and some TCP, atomic multicast should still work just fine.

**Comment by KenBirman** [comment]
I agree.  Basically, it is probably either easy to do this, or impossible to do this!  And it will depend entirely on whether LibFabrics already supports the needed functionality.

**Comment by etremel** [comment]
Commit 3ee59730da83505fd9d867059b0a40ee4c8e0c66 says it closes this issue, but Git didn't notice and auto-close it. (The exact text has to be "closes #60", not "closes issue #60").
