### ISSUE TITLE
 Cooked send's promise is absence when local result is ready.

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#77]
Identified this with Sagar: In `RPCManager::rpc_manager_handler()`, if the sender is local `sender_id == nid`, `toFulfillQueue`, the queue for promises accepting results, is SOMETIMES empty, which causes crash. The reason is: a message is sent first and then prepare the promises in `toFulfillQueue`; however, a local node could response so fast that it calculated the result and try to insert its result to the promise before the promise is prepared (by locking the guard on `toFulfillQueue`). We need to prepare the promise before sending the message.

**Comment by sagarjha** [comment]
Closed by fixing #78 and removing possibility of a race condition in using `toFulfillQueue` and `FulfilledList` even though that race condition is infinitely rare.
