### ISSUE TITLE
Automatic null sends causes deadlock

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#78]
Automatic null sends was intended to prevent deadlock in case a sender is not sending messages actively. It instead causes deadlock in a very subtle way. This may be the stupidest mistake I have ever made ("may be" only because I do not remember all of them).
Whenever we need to send a null message, we follow an accelerated path where we reserve a buffer, update some of the internal counters and call send. We hold the required lock before we do that. The normal send is actually a two-step process. First the user program obtains a buffer and generates a message in it. Whenever it is ready, it calls send. The problem is that null message sends may intercept the user program obtaining a buffer and sending a message. This causes havoc.
Let's consider a very specific example. The user asks for a buffer and gets the buffer number 0. Now, the user writes the message, say "Hello", to buffer 0. Now, a null message is sent. By our logic, it will send buffer 0 and move the next buffer position to 1. But buffer 0 does not contain a null message, but the user's message "Hello". Thus, user's message is sent even before they called send! When they call send, message 2 which is a null message is sent. Fixing this will fix issue #77.
Now, with everything these days, the solution to this problem is something I have been intending to do for some time. I have been meaning to reconcile the two step process of sending a message into one single send which accepts a lambda that the user supplies. This lambda generates the message and we call this internally in send. The difference in this case is that the required lock is held for the entire duration in which the send is being performed.
This is part of my suggested fix for feature #70.

**Comment by KenBirman** [comment]
I really like this bug, and think you should actually call it a “feature”: In some situations, Derecho further reduces latency by sending messages for you before your code has finished preparing the send buffer.  The advantage of this optimization is that it permits negative delay, depending on how early Derecho does the send. A small disadvantage is that the message might be partial or incomprehensible, but how many applications check every single bit, in any case?  In our experimental tests, almost nobody even notices!
