### ISSUE TITLE
Clean up the log files

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#82]
We write the view to disk for fault tolerance. We also write the subgroup states to disk if the application is using `persistent<T>` variables in those subgroups. Then when we start our application, it checks if there are stored log files and if yes, builds the state from the log files as appropriate for a restart case.
While this is great, some of our applications in `applications/demos` and `applications/tests` are short-lived derecho groups that exit once they are done with their purpose. They aren't meant to work well with restarts. Furthermore, if we start one application which exits peacefully and then start another application without deleting the log files, the second application segfaults as it does not how to make sense of the logs. It is a nuisance to manually delete the log files every time we run an application for testing purposes.
For applications that have nothing to do with restart, we should
a) Delete the log files in the beginning of main. The log file location can be obtained from the configuration variable `CONF_PERS_FILE_PATH`.
b) Delete the log files at the end of main when the group object has been destroyed. This will help applications that are started afterwards which do care about the log files.
Note that this is a per-application fix, not a library fix, since we want the fresh start and restart case to look exactly similar from the Derecho API level: Check if log files exist and adjust accordingly. This is so that the applications that do require restart need not make any extra adjustments.

**Comment by songweijia** [comment]
I suggest add persistent state detection in the application layer. At start up, the testers which do not require the persistent state, they are responsible for cleaning it up.  For those may need the state, detect if the persistent state exists and keep or clean it accordingly.

**Comment by sagarjha** [comment]
Okay, does this mean that if I run `bandwidth_test` which writes the log files and then I start `objstore`, `objstore` will figure out that the log file isn't relevant to it and clean it?

**Comment by songweijia** [comment]
No. `objstore` will not do that. Actually, I discourage applications sharing a same persistent folder. But now this is what you can do with `bandwidth_test` now (in commit 2647d45):
```
./bandwidth_test --PERS/reset=true -- 2 0 1000 0
```
In such case, the persistent data will be cleaned.

**Comment by KenBirman** [comment]
This is something to document now, while it is on your mind!
