### ISSUE TITLE
Eliminate all persistence when there are no Persistent fields

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#86]
Right now, ViewManager persists Views and RaggedTrims to disk every time there is a view change, in order to ensure that the restart leader can re-construct the last View when restarting the system from a total failure. However, in the case where there is no persistent state that will need to be recovered after a total failure (i.e. none of the Group's Replicated Objects have any Persistent fields), this is unnecessary because the total restart logic will never need to run. We should tell ViewManager (when it is constructed) whether any Replicated Objects have any persistent fields, and only persist system information to disk if they do.

**Comment by KenBirman** [comment]
You could also leave the logic as is, but do this:  std::fstream.rdbuf( NULL ); where fstream is the file stream you normally would have connected to the log file...

**Comment by songweijia** [comment]
Edward, will this work?
```cpp
if constexp (std::is_base_of<derecho::PersistsFields,T> ) {
  // with persistent state
} else {
  // without
}
```

**Comment by etremel** [comment]
Yes, Weijia, that's exactly what I'm going to do. It's just a little more complicated than that because ViewManager doesn't know the types of any of the Replicated Objects, so Group\<T...\> will have to tell it whether `std::is_base_of<derecho::PersistsFields, T>` is true for any T.
