### ISSUE TITLE
Occasional stall in predicate evaluation thread

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#93]
The predicate evaluation thread seems to hang for about 1ms at unpredictable intervals. This means the latency of small multicasts can occasionally spike to 1ms instead of 1.25 microseconds. Ken thinks this might result from integrating some of Weijia's object store logic last summer, and it might be some sort of delay associated with a system call such as `fsync` or `ioctl` that interacts with disk storage.

**Comment by sagarjha** [comment]
There is an exact 1 ms sleep if the predicates do not fire for 1000 iterations or something. If you remember, this is to reduce CPU usage that the reviewers cried about.

**Comment by sagarjha** [comment]
I verified that the predicate thread is not sleeping. This is as expected. Still the latencies are high. I will investigate.

**Comment by sagarjha** [comment]
@etremel Can I know in which experiment did you see this happening? `latency_test` which is continuously sending messages does not have this issue.

**Comment by sagarjha** [comment]
Okay, I close this issue. We will track the high latency numbers in another thread.
